// board_gpio_handles.h
#pragma once
#include "Driver_GPIO.h"

// Declarations ONLY. No storage here.

extern ARM_DRIVER_GPIO *BOARD_LED_TOP_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_LED_BOT_GPIO_GPIOdrv;

extern ARM_DRIVER_GPIO *BOARD_IOHEADER_GPIOdrv;

extern ARM_DRIVER_GPIO *BOARD_CAM_TRIG_IN_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_DGPIO_GPIO_GPIOdrv;

extern ARM_DRIVER_GPIO *BOARD_CAM_ULP_ENB_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_ULP_TH_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_ULP_RST_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_ULP_WAKEUP_GPIO_GPIOdrv;

extern ARM_DRIVER_GPIO *BOARD_CAM_RESET_GPIO_GPIOdrv;   // RSTN
extern ARM_DRIVER_GPIO *BOARD_CAM_PXRSTN_GPIO_GPIOdrv;  // TX disable

extern ARM_DRIVER_GPIO *BOARD_CAM_PSU_EN_1V1_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_PSU_EN_1V8_GPIO_GPIOdrv;
extern ARM_DRIVER_GPIO *BOARD_CAM_PSU_EN_2V5_GPIO_GPIOdrv;

extern ARM_DRIVER_GPIO *BOARD_USER_BUTTON_GPIO_GPIOdrv;
#ifdef BOARD_VSYNC_INTERRUPT_GPIO_PORT
extern ARM_DRIVER_GPIO *VSYNC_GPIO_drv;
#endif
