/******************************************************************************
* @file     resources.h
* @author   Auto generated by Conductor Tool https://conductor.alifsemi.com/
* @version  v1.0.0
* @date     2025-4-11
* @brief    Firewall and DMA settings for "DevKit Gen 2 (DK-E7)" project with AE722F80F55D5LS
* @bug      None.
* @note     None.
******************************************************************************/
/* 
*   Copyright (C) 2025 Alif Semiconductor - All Rights Reserved.
*   Use, distribution and modification of this code is permitted under the
*   terms stated in the Alif Semiconductor Software License Agreement
*
*   You should have received a copy of the Alif Semiconductor Software
*   License Agreement with this file. If not, please write to:
*   https://alifsemi.com/contact/, or visit: https://alifsemi.com/license/
*/

#ifndef __RESOURCES_H__
#define __RESOURCES_H__

#include <stdint.h>
/* =========================================================================================================================== */
/* ================                                TrustZone Region Settings                                  ================ */
/* =========================================================================================================================== */

/* Region Settings */
#define SAU_REGIONS_MAX					32			/* maximum number of SAU regions */
#define SAU_INIT_CTRL_ENABLE			1			/* Enable/disable the SAU - 0: Disable, 1: Enable SAU */
#define SAU_INIT_CTRL_ALLNS				0			/* Value for SAU_CTRL register bit ALLNS - 0: all Memory is Secure (FW en),  1: all Memory is Non-Secure (FW dis) */

/* FC0 () Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    SEUART */
#define SAU_FC0_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC0_START1 			0x00000000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC0_END1 				0x-1	/* End address of SAU Region 1 */
#define SAU_INIT_FC0_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC0_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC0_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC0_MASTERPER1 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC4 (XNVM) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:       USB */
/* Slaves Modules:    SRAM1 */
#define SAU_FC4_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC4_START1 			0x08000000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC4_END1 				0x0827FFFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC4_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC4_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC4_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC4_MASTERPER1 		900			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC5 (CVM) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:       USB */
/* Slaves Modules:    SRAM0 */
#define SAU_FC5_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC5_START1 			0x02000000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC5_END1 				0x023FFFFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC5_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC5_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC5_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC5_MASTERPER1 		900			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO2 */
#define SAU_FC11_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START1 			0x49002000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC11_END1 				0x49002FFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC11_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER1 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 2 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO6 */
#define SAU_FC11_REGION2 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START2 			0x49006000	/* Start address of SAU Region 2 */
#define SAU_INIT_FC11_END2 				0x49006FFF	/* End address of SAU Region 2 */
#define SAU_INIT_FC11_NSC2 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM2 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER2 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER2 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 3 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO7 */
#define SAU_FC11_REGION3 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START3 			0x49007000	/* Start address of SAU Region 3 */
#define SAU_INIT_FC11_END3 				0x49007FFF	/* End address of SAU Region 3 */
#define SAU_INIT_FC11_NSC3 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM3 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER3 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER3 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 4 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO9 */
#define SAU_FC11_REGION4 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START4 			0x49009000	/* Start address of SAU Region 4 */
#define SAU_INIT_FC11_END4 				0x49009FFF	/* End address of SAU Region 4 */
#define SAU_INIT_FC11_NSC4 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM4 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER4 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER4 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 5 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO11 */
#define SAU_FC11_REGION5 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START5 			0x4900B000	/* Start address of SAU Region 5 */
#define SAU_INIT_FC11_END5 				0x4900BFFF	/* End address of SAU Region 5 */
#define SAU_INIT_FC11_NSC5 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM5 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER5 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER5 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 6 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    GPIO12 */
#define SAU_FC11_REGION6 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START6 			0x4900C000	/* Start address of SAU Region 6 */
#define SAU_INIT_FC11_END6 				0x4900CFFF	/* End address of SAU Region 6 */
#define SAU_INIT_FC11_NSC6 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM6 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER6 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER6 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 7 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    LPGPIO */
#define SAU_FC11_REGION7 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START7 			0x42002000	/* Start address of SAU Region 7 */
#define SAU_INIT_FC11_END7 				0x42002FFF	/* End address of SAU Region 7 */
#define SAU_INIT_FC11_NSC7 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM7 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER7 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER7 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 8 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    LPCPI */
#define SAU_FC11_REGION8 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START8 			0x43003000	/* Start address of SAU Region 8 */
#define SAU_INIT_FC11_END8 				0x43003FFF	/* End address of SAU Region 8 */
#define SAU_INIT_FC11_NSC8 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM8 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER8 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER8 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 9 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    I2C0 */
#define SAU_FC11_REGION9 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START9 			0x49010000	/* Start address of SAU Region 9 */
#define SAU_INIT_FC11_END9 				0x49010FFF	/* End address of SAU Region 9 */
#define SAU_INIT_FC11_NSC9 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM9 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER9 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER9 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 10 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    I2C2 */
#define SAU_FC11_REGION10 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START10 			0x49012000	/* Start address of SAU Region 10 */
#define SAU_INIT_FC11_END10 				0x49012FFF	/* End address of SAU Region 10 */
#define SAU_INIT_FC11_NSC10 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM10 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER10 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER10 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 11 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    SPI1 */
#define SAU_FC11_REGION11 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START11 			0x48104000	/* Start address of SAU Region 11 */
#define SAU_INIT_FC11_END11 				0x48104FFF	/* End address of SAU Region 11 */
#define SAU_INIT_FC11_NSC11 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM11 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER11 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER11 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 12 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    UART1 */
#define SAU_FC11_REGION12 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START12 			0x49019000	/* Start address of SAU Region 12 */
#define SAU_INIT_FC11_END12 				0x49019FFF	/* End address of SAU Region 12 */
#define SAU_INIT_FC11_NSC12 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM12 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER12 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER12 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 13 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    USB */
#define SAU_FC11_REGION13 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START13 			0x48200000	/* Start address of SAU Region 13 */
#define SAU_INIT_FC11_END13 				0x482FFFFF	/* End address of SAU Region 13 */
#define SAU_INIT_FC11_NSC13 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM13 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER13 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER13 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 14 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    UTIMER10 */
#define SAU_FC11_REGION14 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START14 			0x48000000	/* Start address of SAU Region 14 */
#define SAU_INIT_FC11_END14 				0x480FFFFF	/* End address of SAU Region 14 */
#define SAU_INIT_FC11_NSC14 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM14 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER14 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER14 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC13 (OCVM) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    OSPI1 */
#define SAU_FC13_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC13_START1 			0x83002000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC13_END1 				0x83002FFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC13_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC13_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC13_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC13_MASTERPER1 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC14 (DEBUG) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    JTAG */
#define SAU_FC14_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC14_START1 			0x00000000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC14_END1 				0xFFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC14_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC14_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC14_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC14_MASTERPER1 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */




/* =========================================================================================================================== */
/* ================                                DMA Definitions                                            ================ */
/* =========================================================================================================================== */

/* Callback DMA Macro */
#define SET_DMA_REGISTER(reg, mask, value)  {*(uint32_t*)(reg) &= ~((uint32_t)(mask));\
                                            *(uint32_t*)(reg) |= (uint32_t)(value);}

#endif /* __RESOURCES_H__ */
