/* 
*   Copyright (C) 2025 Alif Semiconductor - All Rights Reserved.
*   Use, distribution and modification of this code is permitted under the
*   terms stated in the Alif Semiconductor Software License Agreement
*
*   You should have received a copy of the Alif Semiconductor Software
*   License Agreement with this file. If not, please write to:
*   https://alifsemi.com/contact/, or visit: https://alifsemi.com/license/
*/
/******************************************************************************
* @file    	pins.h
* @author  	Auto generated by Conductor Tool https://conductor.alifsemi.com/
* @version  v1.0.0
* @date     2025-3-11
* @brief   	Pin MUX and Pin Config settings for "DevKit Gen 2 (DK-E7)"
*           project with AE722F80F55D5LS.
* @bug      None.
* @note     None.
******************************************************************************/

#ifndef __PINS_H__
#define __PINS_H__

#include <stdint.h>
#include "pinconf.h"

struct pinconf {
    uint8_t port;
    uint8_t pin;
    uint8_t alternate_function;
    uint8_t pad_control;
};

/* Pin Mux and Config Values generated by Conductor Tool */

const struct pinconf board_pinconf[] = {
	/* P0_0 on pin R19. Functions: [0]: GPIO0_0, [1]: OSPI0_D0_A, [2]: UART0_RX_A, [3]: I3C_SDA_A, [4]: >>>UT0_T0_A<<<, [5]: LPCAM_HSYNC_B, [6]: CAM_HSYNC_A, [7]: ANA_S0 */
	/* Selected: UT0_T0_A for "Capture Mode" */
	{PORT_0, PIN_0, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P0_1 on pin R13. Functions: [0]: GPIO0_1, [1]: OSPI0_D1_A, [2]: UART0_TX_A, [3]: I3C_SCL_A, [4]: >>>UT0_T1_A<<<, [5]: LPCAM_VSYNC_B, [6]: CAM_VSYNC_A, [7]: ANA_S1 */
	/* Selected: UT0_T1_A for "Capture Mode" */
	{PORT_0, PIN_1, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P0_4 on pin R10. Functions: [0]: GPIO0_4, [1]: OSPI0_D4_A, [2]: UART1_RX_A, [3]: PDM_D0_A, [4]: I2C1_SDA_A, [5]: >>>UT2_T0_A<<<, [6]: CAN_RXD_B, [7]: ANA_S4 */
	/* Selected: UT2_T0_A for "Trigger Mode" */
	{PORT_0, PIN_4, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P0_5 on pin N15. Functions: [0]: GPIO0_5, [1]: OSPI0_D5_A, [2]: UART1_TX_A, [3]: PDM_C0_A, [4]: I2C1_SCL_A, [5]: >>>UT2_T1_A<<<, [6]: CAN_TXD_B, [7]: ANA_S5 */
	/* Selected: UT2_T1_A for "Trigger Mode" */
	{PORT_0, PIN_5, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P0_6 on pin P15. Functions: [0]: GPIO0_6, [1]: OSPI0_D6_A, [2]: UART1_CTS_A, [3]: PDM_D1_A, [4]: I2C2_SCL_A, [5]: UT3_T0_A, [6]: CAN_STBY_B, [7]: >>>ANA_S6<<< */
	/* Selected: ANA_S6 for "CLICKBOARD_ANA". Can be used with ADC121_IN0 (ADC121 input 0); ADC24_IN2_N (ADC24 differential input 2 negative); CMP0_IN1 (CMP0 input 1) */
	{PORT_0, PIN_6, PINMUX_ALTERNATE_FUNCTION_7, 0},

	/* P0_7 on pin R15. Functions: [0]: GPIO0_7, [1]: OSPI0_D7_A, [2]: UART1_RTS_A, [3]: PDM_C1_A, [4]: I2C2_SDA_A, [5]: UT3_T1_A, [6]: CDC_DE_B, [7]: >>>ANA_S7<<< */
	/* Selected: ANA_S7 for "POTENTIOMETER". Can be used with ADC121_IN1 (ADC121 input 1); ADC24_IN3_N (ADC24 differential input 3 negative); CMP1_IN1 (CMP1 input 1) */
	{PORT_0, PIN_7, PINMUX_ALTERNATE_FUNCTION_7, 0},

	/* P3_4 on pin F2. Functions: [0]: GPIO3_4, [1]: OSPI0_RXDS_A, [2]: UART5_RX_A, [3]: LPPDM_C0_B, [4]: I2S1_SCLK_A, [5]: >>>I2C0_SCL_B<<<, [6]: QEC1_Y_A, [7]: CAM_D8_A */
	/* Selected: I2C0_SCL_B for "Clickboard,Slave" */
	{PORT_3, PIN_4, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P3_5 on pin F1. Functions: [0]: GPIO3_5, [1]: OSPI0_SCLKN_A, [2]: UART5_TX_A, [3]: LPPDM_D0_B, [4]: SPI0_SS1_B, [5]: >>>I2C0_SDA_B<<<, [6]: QEC1_Z_A, [7]: CAM_D9_A */
	/* Selected: I2C0_SDA_B for "Clickboard,Slave" */
	{PORT_3, PIN_5, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P4_4 on pin B17. Functions: [0]: GPIO4_4, [1]: >>>JTAG_TCK<<<, [2]: I2S0_WS_B, [3]: SPI2_SCLK_A, [4]: FAULT0_A */
	/* Selected: JTAG_TCK for "My JTAG" */
	{PORT_4, PIN_4, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P4_5 on pin A19. Functions: [0]: GPIO4_5, [1]: >>>JTAG_TMS<<<, [2]: SPI2_SS0_A, [3]: FAULT1_A */
	/* Selected: JTAG_TMS for "My JTAG" */
	{PORT_4, PIN_5, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P4_6 on pin A18. Functions: [0]: GPIO4_6, [1]: >>>JTAG_TDI<<<, [2]: SPI2_SS1_A, [3]: FAULT2_A */
	/* Selected: JTAG_TDI for "My JTAG" */
	{PORT_4, PIN_6, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P4_7 on pin B16. Functions: [0]: GPIO4_7, [1]: >>>JTAG_TDO<<<, [2]: SPI2_SS2_A, [3]: FAULT3_A */
	/* Selected: JTAG_TDO for "My JTAG" */
	{PORT_4, PIN_7, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P5_6 on pin B12. Functions: [0]: GPIO5_6, [1]: UART1_CTS_B, [2]: I2C2_SCL_C, [3]: >>>UT3_T0_B<<<, [4]: SD_D6_A, [5]: ETH_RXD1_A, [6]: CDC_VSYNC_A */
	/* Selected: UT3_T0_B for "Clickboard PWM" */
	{PORT_5, PIN_6, PINMUX_ALTERNATE_FUNCTION_3, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P7_2 on pin D1. Functions: [0]: GPIO7_2, [1]: Reserved, [2]: UART3_CTS_B, [3]: CMP1_OUT_A, [4]: SPI0_SCLK_C, [5]: >>>I2C1_SDA_C<<<, [6]: UT9_T0_B, [7]: SD_RST_A */
	/* Selected: I2C1_SDA_C for "Camera,GT911 Touchscreen,Master" */
	{PORT_7, PIN_2, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P7_3 on pin A8. Functions: [0]: GPIO7_3, [1]: Reserved, [2]: UART3_RTS_B, [3]: CMP0_OUT_A, [4]: SPI0_SS0_C, [5]: >>>I2C1_SCL_C<<<, [6]: UT9_T1_B, [7]: CAN_STBY_A */
	/* Selected: I2C1_SCL_C for "Camera,GT911 Touchscreen,Master" */
	{PORT_7, PIN_3, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_12MA},

	/* P8_0 on pin B7. Functions: [0]: GPIO8_0, [1]: OSPI1_SCLKN_C, [2]: AUDIO_CLK_A, [3]: FAULT0_B, [4]: >>>LPCAM_D0_A<<<, [5]: SD_D0_C, [6]: CDC_D0_A, [7]: CAM_D0_B */
	/* Selected: LPCAM_D0_A for "genx320cpi" */
	{PORT_8, PIN_0, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_1 on pin C2. Functions: [0]: GPIO8_1, [1]: I2S2_SDI_A, [2]: FAULT1_B, [3]: >>>LPCAM_D1_A<<<, [4]: SD_D1_C, [5]: CDC_D1_A, [6]: CAM_D1_B */
	/* Selected: LPCAM_D1_A for "genx320cpi" */
	{PORT_8, PIN_1, PINMUX_ALTERNATE_FUNCTION_3, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_2 on pin C3. Functions: [0]: GPIO8_2, [1]: I2S2_SDO_A, [2]: SPI0_SS3_B, [3]: FAULT2_B, [4]: >>>LPCAM_D2_A<<<, [5]: SD_D2_C, [6]: CDC_D2_A, [7]: CAM_D2_B */
	/* Selected: LPCAM_D2_A for "genx320cpi" */
	{PORT_8, PIN_2, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_3 on pin A7. Functions: [0]: GPIO8_3, [1]: I2S2_SCLK_A, [2]: SPI1_MISO_B, [3]: FAULT3_B, [4]: >>>LPCAM_D3_A<<<, [5]: SD_D3_C, [6]: CDC_D3_A, [7]: CAM_D3_B */
	/* Selected: LPCAM_D3_A for "genx320cpi" */
	{PORT_8, PIN_3, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_4 on pin B4. Functions: [0]: GPIO8_4, [1]: I2S2_WS_A, [2]: SPI1_MOSI_B, [3]: QEC0_X_B, [4]: >>>LPCAM_D4_A<<<, [5]: SD_D4_C, [6]: CDC_D4_A, [7]: CAM_D4_B */
	/* Selected: LPCAM_D4_A for "genx320cpi" */
	{PORT_8, PIN_4, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_5 on pin H1. Functions: [0]: GPIO8_5, [1]: Reserved, [2]: SPI1_SCLK_B, [3]: QEC0_Y_B, [4]: >>>LPCAM_D5_A<<<, [5]: SD_D5_C, [6]: CDC_D5_A, [7]: CAM_D5_B */
	/* Selected: LPCAM_D5_A for "genx320cpi" */
	{PORT_8, PIN_5, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_6 on pin J2. Functions: [0]: GPIO8_6, [1]: Reserved, [2]: I2S3_SCLK_B, [3]: QEC0_Z_B, [4]: >>>LPCAM_D6_A<<<, [5]: SD_D6_C, [6]: CDC_D6_A, [7]: CAM_D6_B */
	/* Selected: LPCAM_D6_A for "genx320cpi" */
	{PORT_8, PIN_6, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P8_7 on pin J1. Functions: [0]: GPIO8_7, [1]: Reserved, [2]: I2S3_WS_B, [3]: QEC1_X_B, [4]: >>>LPCAM_D7_A<<<, [5]: SD_D7_C, [6]: CDC_D7_A, [7]: CAM_D7_B */
	/* Selected: LPCAM_D7_A for "genx320cpi" */
	{PORT_8, PIN_7, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P10_0 on pin M2. Functions: [0]: GPIO10_0, [1]: OSPI1_D3_C, [2]: UART6_DE_B, [3]: SPI2_SS3_B, [4]: UT0_T0_C, [5]: >>>LPCAM_HSYNC_A<<<, [6]: CDC_D16_A, [7]: CAM_HSYNC_B */
	/* Selected: LPCAM_HSYNC_A for "genx320cpi" */
	{PORT_10, PIN_0, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P10_1 on pin M1. Functions: [0]: GPIO10_1, [1]: OSPI1_D4_C, [2]: Reserved, [3]: LPI2S_SDI_B, [4]: UT0_T1_C, [5]: >>>LPCAM_VSYNC_A<<<, [6]: CDC_D17_A, [7]: CAM_VSYNC_B */
	/* Selected: LPCAM_VSYNC_A for "genx320cpi" */
	{PORT_10, PIN_1, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P10_2 on pin N1. Functions: [0]: GPIO10_2, [1]: OSPI1_D5_C, [2]: Reserved, [3]: LPI2S_SDO_B, [4]: UT1_T0_C, [5]: >>>LPCAM_PCLK_A<<<, [6]: CDC_D18_A, [7]: CAM_PCLK_B */
	/* Selected: LPCAM_PCLK_A for "genx320cpi" */
	{PORT_10, PIN_2, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P10_3 on pin N2. Functions: [0]: GPIO10_3, [1]: OSPI1_D6_C, [2]: Reserved, [3]: LPI2S_SCLK_B, [4]: UT1_T1_C, [5]: >>>LPCAM_XVCLK_A<<<, [6]: CDC_D19_A, [7]: CAM_XVCLK_B */
	/* Selected: LPCAM_XVCLK_A for "genx320cpi" */
	{PORT_10, PIN_3, PINMUX_ALTERNATE_FUNCTION_5, PADCTRL_DRIVER_DISABLED_BUS_REPEATER | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P10_7 on pin P1. Functions: [0]: GPIO10_7, [1]: UART7_RX_A, [2]: I2S2_SCLK_B, [3]: SPI3_SCLK_B, [4]: I2C1_SCL_D, [5]: UT3_T1_C, [6]: CDC_D23_A, [7]: >>>OSPI1_RXDS_C<<< */
	/* Selected: OSPI1_RXDS_C for "ISSI Flash" */
	{PORT_10, PIN_7, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_READ_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P12_1 on pin E18. Functions: [0]: GPIO12_1, [1]: OSPI0_SCLKN_C, [2]: >>>UART4_RX_B<<<, [3]: I2S1_SDO_B, [4]: UT8_T1_C, [5]: CDC_D9_B */
	/* Selected: UART4_RX_B for "UARTB" */
	{PORT_12, PIN_1, PINMUX_ALTERNATE_FUNCTION_2, PADCTRL_READ_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P12_2 on pin E15. Functions: [0]: GPIO12_2, [1]: OSPI0_RXDS_C, [2]: >>>UART4_TX_B<<<, [3]: I2S1_SCLK_B, [4]: UT9_T0_C, [5]: CDC_D10_B */
	/* Selected: UART4_TX_B for "UARTB" */
	{PORT_12, PIN_2, PINMUX_ALTERNATE_FUNCTION_2, PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P13_0 on pin G18. Functions: [0]: GPIO13_0, [1]: OSPI1_D0_B, [2]: Reserved, [3]: SPI3_SS1_A, [4]: >>>QEC0_X_C<<<, [5]: SD_D0_B, [6]: CDC_D16_B */
	/* Selected: QEC0_X_C for "Encoder" */
	{PORT_13, PIN_0, PINMUX_ALTERNATE_FUNCTION_4, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P13_1 on pin G15. Functions: [0]: GPIO13_1, [1]: OSPI1_D1_B, [2]: SPI3_SS2_A, [3]: >>>QEC0_Y_C<<<, [4]: SD_D1_B, [5]: CDC_D17_B */
	/* Selected: QEC0_Y_C for "Encoder" */
	{PORT_13, PIN_1, PINMUX_ALTERNATE_FUNCTION_3, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P13_2 on pin F15. Functions: [0]: GPIO13_2, [1]: OSPI1_D2_B, [2]: SPI3_SS3_A, [3]: >>>QEC0_Z_C<<<, [4]: SD_D2_B, [5]: CDC_D18_B */
	/* Selected: QEC0_Z_C for "Encoder" */
	{PORT_13, PIN_2, PINMUX_ALTERNATE_FUNCTION_3, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P14_4 on pin R8. Functions: [0]: GPIO14_4, [1]: >>>CMP3_OUT_B<<<, [2]: SPI1_MISO_C, [3]: FAULT0_C */
	/* Selected: CMP3_OUT_B for "CMP3_OUT" */
	{PORT_14, PIN_4, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P14_5 on pin L11. Functions: [0]: GPIO14_5, [1]: >>>CMP2_OUT_B<<<, [2]: SPI1_MOSI_C, [3]: FAULT1_C */
	/* Selected: CMP2_OUT_B for "CMP2_OUT" */
	{PORT_14, PIN_5, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P14_6 on pin K12. Functions: [0]: GPIO14_6, [1]: >>>CMP1_OUT_B<<<, [2]: SPI1_SCLK_C, [3]: FAULT2_C */
	/* Selected: CMP1_OUT_B for "CMP1_OUT" */
	{PORT_14, PIN_6, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P14_7 on pin L12. Functions: [0]: GPIO14_7, [1]: >>>CMP0_OUT_B<<<, [2]: SPI1_SS0_C, [3]: FAULT3_C */
	/* Selected: CMP0_OUT_B for "CMP0_OUT" */
	{PORT_14, PIN_7, PINMUX_ALTERNATE_FUNCTION_1, PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_0 on pin V2 {FLEX IO}. Functions: [0]: >>>GPIOV_0<<<, [1]: LPTMR0_CLK_IO. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_0 for "JOY_SW_A" */
	{PORT_15, PIN_0, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_1 on pin W2 {FLEX IO}. Functions: [0]: >>>GPIOV_1<<<, [1]: LPTMR1_CLK_OUT. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_1 for "JOY_SW_B" */
	{PORT_15, PIN_1, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_2 on pin U2 {FLEX IO}. Functions: [0]: >>>GPIOV_2<<<, [1]: LPTMR2_CLK_IO. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_2 for "JOY_SW_C" */
	{PORT_15, PIN_2, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_3 on pin V1 {FLEX IO}. Functions: [0]: >>>GPIOV_3<<<, [1]: LPTMR3_CLK_OUT. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_3 for "JOY_SW_D" */
	{PORT_15, PIN_3, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_4 on pin V3. Functions: [0]: >>>GPIOV_4<<<. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_4 for "JOY_SW_CENTER" */
	{PORT_15, PIN_4, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_READ_ENABLE | PADCTRL_SCHMITT_TRIGGER_ENABLE | PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_5 on pin W4. Functions: [0]: >>>GPIOV_5<<<. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_5 for "LCD_RESET" */
	{PORT_15, PIN_5, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_6 on pin V4. Functions: [0]: >>>GPIOV_6<<<. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_6 for "OSPI0_RESET" */
	{PORT_15, PIN_6, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA},

	/* P15_7 on pin W5. Functions: [0]: >>>GPIOV_7<<<. Note that LPGPIO_CTRL_n register has a different layout! */
	/* Selected: GPIOV_7 for "OSPI1_RESET" */
	{PORT_15, PIN_7, PINMUX_ALTERNATE_FUNCTION_0, PADCTRL_DRIVER_DISABLED_PULL_UP | PADCTRL_OUTPUT_DRIVE_STRENGTH_4MA} 

};

#endif /* __PINS_H__ */
