/******************************************************************************
* @file     resources.h
* @author   Auto generated by Conductor Tool https://conductor.alifsemi.com/
* @version  v1.0.0
* @date     2025-3-11
* @brief    Firewall and DMA settings for "DevKit Gen 2 (DK-E7)" project with AE722F80F55D5LS
* @bug      None.
* @note     None.
******************************************************************************/
/* 
*   Copyright (C) 2025 Alif Semiconductor - All Rights Reserved.
*   Use, distribution and modification of this code is permitted under the
*   terms stated in the Alif Semiconductor Software License Agreement
*
*   You should have received a copy of the Alif Semiconductor Software
*   License Agreement with this file. If not, please write to:
*   https://alifsemi.com/contact/, or visit: https://alifsemi.com/license/
*/

#ifndef __RESOURCES_H__
#define __RESOURCES_H__

#include <stdint.h>
/* =========================================================================================================================== */
/* ================                                TrustZone Region Settings                                  ================ */
/* =========================================================================================================================== */

/* Region Settings */
#define SAU_REGIONS_MAX					32			/* maximum number of SAU regions */
#define SAU_INIT_CTRL_ENABLE			1			/* Enable/disable the SAU - 0: Disable, 1: Enable SAU */
#define SAU_INIT_CTRL_ALLNS				1			/* Value for SAU_CTRL register bit ALLNS - 0: all Memory is Secure (FW en),  1: all Memory is Non-Secure (FW dis) */

/* FC11 (EXPMST0) Region 1 */
/* Master Cores:      M55-HE */
/* Master Pers:        */
/* Slaves Modules:    LPCPI */
#define SAU_FC11_REGION1 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START1 			0x43003000	/* Start address of SAU Region 1 */
#define SAU_INIT_FC11_END1 				0x43003FFF	/* End address of SAU Region 1 */
#define SAU_INIT_FC11_NSC1 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM1 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER1 			17			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER1 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */


/* FC11 (EXPMST0) Region 2 */
/* Master Cores:      A32 */
/* Master Pers:        */
/* Slaves Modules:    UART4 */
#define SAU_FC11_REGION2 				1			/* Initialize SAU region - 0: False, 1: True */
#define SAU_INIT_FC11_START2 			0x4901C000	/* Start address of SAU Region 2 */
#define SAU_INIT_FC11_END2 				0x4901CFFF	/* End address of SAU Region 2 */
#define SAU_INIT_FC11_NSC2 				1			/* Non-Secure callable enabled - 0: False, 1: True */
#define SAU_INIT_FC11_PERM2 			0xFFF		/* Region permissions - R W X | S NS | P U - (see RGN_MPLn Register)*/
#define SAU_INIT_FC11_MASTER2 			1			/* Region Master ID - 0: N/A, 1: A32, 16: M55-HP/BLE, 17: M55-HE, 0xFF: Shared */
#define SAU_INIT_FC11_MASTERPER2 		0			/* Region Master Peripheral ID - 0: N/A, 900: USB, 901: DMA0_SEC, 902: DMA0_NS, 903: ETH, 904: SDMMC, 905: CDC, 906: CPI, 907: GPU2D, 0xFF: Shared */




/* =========================================================================================================================== */
/* ================                                DMA Definitions                                            ================ */
/* =========================================================================================================================== */

/* Callback DMA Macro */
#define SET_DMA_REGISTER(reg, mask, value)  {*(uint32_t*)(reg) &= ~((uint32_t)(mask));\
                                            *(uint32_t*)(reg) |= (uint32_t)(value);}

#endif /* __RESOURCES_H__ */
