/* 
*   Copyright (C) 2025 Alif Semiconductor - All Rights Reserved.
*   Use, distribution and modification of this code is permitted under the
*   terms stated in the Alif Semiconductor Software License Agreement
*
*   You should have received a copy of the Alif Semiconductor Software
*   License Agreement with this file. If not, please write to:
*   https://alifsemi.com/contact/, or visit: https://alifsemi.com/license/
*/
/******************************************************************************
* @file     board_defs.h
* @author  	Auto generated by Conductor Tool https://conductor.alifsemi.com/
* @version  v1.0.1
* @date     2025-4-11
* @brief    Board info/settings for "DevKit Gen 2 (DK-E7)" project
*           with AE722F80F55D5LS
* @bug      None.
* @note     To modify this file manually, take care to modify pins.h and gpios.h 
*           accordingly when required.
******************************************************************************/
//-------- <<< Use Configuration Wizard in Context Menu >>> -------------------

// <h> Board peripheral instances
// <o> "Clickboard" I2C instance number <0-3>
#define BOARD_CLICKBOARD_I2C_INSTANCE				0

// <o> "Slave" I2C instance number <0-3>
#define BOARD_SLAVE_I2C_INSTANCE				0

// <e> JTAG module enabled flag
#define BOARD_JTAG_ENABLED				1
// </e>

// <e> LPCPI module enabled flag
#define BOARD_LPCPI_ENABLED				1
// </e>

// <e> LPGPIO module enabled flag
#define BOARD_LPGPIO_ENABLED				1
// </e>

// <e> MISC module enabled flag
#define BOARD_MISC_ENABLED				1
// </e>

// <o> "ISSI Flash" OSPI instance number <0-1>
#define BOARD_ISSI_FLASH_OSPI_INSTANCE				1

// <e> SEUART module enabled flag
#define BOARD_SEUART_ENABLED				1
// </e>

// <o> "Slave" SPI instance number <0-3>
#define BOARD_SLAVE_SPI_INSTANCE				1

// <e> USB module enabled flag
#define BOARD_USB_ENABLED				1
// <e> "Device Role" on USB presence flag
#define BOARD_USB_DEVICE_ROLE_PRESENT				1
// </e>
// </e>

// <o> "UTIMER on Pinheader" UTIMER instance number <0-12>
#define BOARD_UTIMER_ON_PINHEADER_UTIMER_INSTANCE				10

// </h>
// <h> Miscellaneous
// <o> Onboard LEDs
// <i> Sets the #define BOARD_LED_COUNT in the board_def.h file exported from the Conductor tool.
#define BOARD_LED_COUNT				0

// <o> Onboard RGB LEDs
// <i> Sets the #define BOARD_LEDRGB_COUNT in the board_def.h file exported from the Conductor tool.
#define BOARD_LEDRGB_COUNT				2

// <o> Onboard Push-buttons
// <i> Sets the #define BOARD_BUTTON_COUNT in the board_def.h file exported from the Conductor tool.
#define BOARD_BUTTON_COUNT				1

// <o> Onboard Config Switches or Jumpers
// <i> Sets the #define BOARD_CONFIG_JUMPER_COUNT in the board_def.h file exported from the Conductor tool.
#define BOARD_CONFIG_JUMPER_COUNT				0

// <o> Onboard Switching Devices
// <i> Sets the #define BOARD_SWITCH_OUTPUT_COUNT in the board_def.h file exported from the Conductor tool. These include relays, solid state relays, transistors, optocopulers, etc.
#define BOARD_SWITCH_OUTPUT_COUNT				0

// <o> OSPI0 Bus Speed
// <i> Selects OSPI0 bus speed for a 200-MHz (default) HCLK. For 100 MHz and lower HCLK clock speeds, some values are either not possible, either rounded to the closest possible value in hardware.
#define BOARD_OSPI0_BUS_SPEED				100000000

// <o> OSPI1 Bus Speed
// <i> Selects OSPI1 bus speed for a 200-MHz (default) HCLK. For 100 MHz and lower HCLK clock speeds, some values are either not possible, either rounded to the closest possible value in hardware.
#define BOARD_OSPI1_BUS_SPEED				100000000

// <o> OSPI0 onboard memory size
#define BOARD_OSPI0_MEM_SIZE				33554432

// <o> OSPI1 onboard memory size
#define BOARD_OSPI1_MEM_SIZE				33554432

// </h>
// <h> GPIO port/pin numbers, analog instance/input numbers, etc.
// <o> FLEX IO pins supply voltage <0=> 3.3 V <1=> 1.8 V
// <i> Make sure this setting corresponds to the VDD_IO_FLEX pin voltage. If the VDD_IO_FLEX pin is connected to a 3.3 V supply, do not change the value of the GPIO_CNTL register to command 1.8-V operation mode!
#define FLEX_IO_VOLTAGE_1V8				1

// <o> "LED_BOT" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_LED_BOT_GPIO_PORT				2
// <o> "LED_BOT" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_LED_BOT_GPIO_PIN 				4

// <o> "CAM_PSU_EN_2V5" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_PSU_EN_2V5_GPIO_PORT				2
// <o> "CAM_PSU_EN_2V5" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_PSU_EN_2V5_GPIO_PIN 				5

// <o> "GPIO_PINHEAD" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_GPIO_PINHEAD_GPIO_PORT				6
// <o> "GPIO_PINHEAD" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_GPIO_PINHEAD_GPIO_PIN 				7

// <o> "CAM_RSTN" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_RSTN_GPIO_PORT				7
// <o> "CAM_RSTN" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_RSTN_GPIO_PIN 				3

// <o> "CAM_ULP_RSTN" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_ULP_RSTN_GPIO_PORT				7
// <o> "CAM_ULP_RSTN" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_ULP_RSTN_GPIO_PIN 				4

// <o> "CAM_PXRSTN" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_PXRSTN_GPIO_PORT				7
// <o> "CAM_PXRSTN" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_PXRSTN_GPIO_PIN 				5

// <o> "CAM_ULP_TH" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_ULP_TH_GPIO_PORT				7
// <o> "CAM_ULP_TH" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_ULP_TH_GPIO_PIN 				7

// <o> "CAM_TRIG_IN" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_TRIG_IN_GPIO_PORT				9
// <o> "CAM_TRIG_IN" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_TRIG_IN_GPIO_PIN 				1

// <o> "CAM_HISTO_MODE" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_HISTO_MODE_GPIO_PORT				9
// <o> "CAM_HISTO_MODE" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_HISTO_MODE_GPIO_PIN 				5

// <o> "CAM_ULP_ENb" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_ULP_ENB_GPIO_PORT				11
// <o> "CAM_ULP_ENb" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_ULP_ENB_GPIO_PIN 				2

// <o> "LED_TOP" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_LED_TOP_GPIO_PORT				12
// <o> "LED_TOP" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_LED_TOP_GPIO_PIN 				0

// <o> "USER_PUSH" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_USER_PUSH_GPIO_PORT				15
// <o> "USER_PUSH" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_USER_PUSH_GPIO_PIN 				1

// <o> "CAM_ULP_WAKEUP" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_ULP_WAKEUP_GPIO_PORT				15
// <o> "CAM_ULP_WAKEUP" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_ULP_WAKEUP_GPIO_PIN 				3

// <o> "CAM_DGPIO" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_DGPIO_GPIO_PORT				15
// <o> "CAM_DGPIO" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_DGPIO_GPIO_PIN 				4

// <o> "CAM_PSU_EN_1V8" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_PSU_EN_1V8_GPIO_PORT				15
// <o> "CAM_PSU_EN_1V8" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_PSU_EN_1V8_GPIO_PIN 				5

// <o> "CAM_PSU_EN_1V1" GPIO port number <0=> GPIO0 <1=> GPIO1 <2=> GPIO2 <3=> GPIO3 <4=> GPIO4 <5=> GPIO5 <6=> GPIO6 <7=> GPIO7 <8=> GPIO8 <9=> GPIO9 <10=> GPIO10 <11=> GPIO11 <12=> GPIO12 <13=> GPIO13 <14=> GPIO14 <15=> LPGPIO
#define BOARD_CAM_PSU_EN_1V1_GPIO_PORT				15
// <o> "CAM_PSU_EN_1V1" GPIO pin number <0=> PIN0 <1=> PIN1 <2=> PIN2 <3=> PIN3 <4=> PIN4 <5=> PIN5 <6=> PIN6 <7=> PIN7
#define BOARD_CAM_PSU_EN_1V1_GPIO_PIN 				7


// P0_0 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_0_ADC12_INSTANCE 				0
// P0_0 ADC12 input number (Do Not Modify!)
#define BOARD_P0_0_ADC12_INPUT 				0

// P0_0 ADC24 positive input number (Do Not Modify!)
#define BOARD_P0_0_ADC24_POSITIVE_INPUT 				0

// P0_0 CMP instance number (Do Not Modify!)
#define BOARD_P0_0_CMP_INSTANCE 				0
// P0_0 CMP input number (Do Not Modify!)
#define BOARD_P0_0_CMP_INPUT 				0


// P0_1 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_1_ADC12_INSTANCE 				0
// P0_1 ADC12 input number (Do Not Modify!)
#define BOARD_P0_1_ADC12_INPUT 				1

// P0_1 ADC24 positive input number (Do Not Modify!)
#define BOARD_P0_1_ADC24_POSITIVE_INPUT 				1

// P0_1 CMP instance number (Do Not Modify!)
#define BOARD_P0_1_CMP_INSTANCE 				1
// P0_1 CMP input number (Do Not Modify!)
#define BOARD_P0_1_CMP_INPUT 				0


// P0_2 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_2_ADC12_INSTANCE 				0
// P0_2 ADC12 input number (Do Not Modify!)
#define BOARD_P0_2_ADC12_INPUT 				2

// P0_2 ADC24 positive input number (Do Not Modify!)
#define BOARD_P0_2_ADC24_POSITIVE_INPUT 				2

// P0_2 CMP instance number (Do Not Modify!)
#define BOARD_P0_2_CMP_INSTANCE 				2
// P0_2 CMP input number (Do Not Modify!)
#define BOARD_P0_2_CMP_INPUT 				0


// P0_3 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_3_ADC12_INSTANCE 				0
// P0_3 ADC12 input number (Do Not Modify!)
#define BOARD_P0_3_ADC12_INPUT 				3

// P0_3 ADC24 positive input number (Do Not Modify!)
#define BOARD_P0_3_ADC24_POSITIVE_INPUT 				3

// P0_3 CMP instance number (Do Not Modify!)
#define BOARD_P0_3_CMP_INSTANCE 				3
// P0_3 CMP input number (Do Not Modify!)
#define BOARD_P0_3_CMP_INPUT 				0


// P0_4 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_4_ADC12_INSTANCE 				0
// P0_4 ADC12 input number (Do Not Modify!)
#define BOARD_P0_4_ADC12_INPUT 				4

// P0_4 ADC24 negative input number (Do Not Modify!)
#define BOARD_P0_4_ADC24_NEGATIVE_INPUT 				0

// P0_4 CMP instance number (Do Not Modify!)
#define BOARD_P0_4_CMP_INSTANCE 				0
// P0_4 CMP input number (Do Not Modify!)
#define BOARD_P0_4_CMP_INPUT 				3


// P0_5 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_5_ADC12_INSTANCE 				0
// P0_5 ADC12 input number (Do Not Modify!)
#define BOARD_P0_5_ADC12_INPUT 				5

// P0_5 ADC24 negative input number (Do Not Modify!)
#define BOARD_P0_5_ADC24_NEGATIVE_INPUT 				1

// P0_5 CMP instance number (Do Not Modify!)
#define BOARD_P0_5_CMP_INSTANCE 				1
// P0_5 CMP input number (Do Not Modify!)
#define BOARD_P0_5_CMP_INPUT 				3


// P0_6 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_6_ADC12_INSTANCE 				1
// P0_6 ADC12 input number (Do Not Modify!)
#define BOARD_P0_6_ADC12_INPUT 				0

// P0_6 ADC24 negative input number (Do Not Modify!)
#define BOARD_P0_6_ADC24_NEGATIVE_INPUT 				2

// P0_6 CMP instance number (Do Not Modify!)
#define BOARD_P0_6_CMP_INSTANCE 				0
// P0_6 CMP input number (Do Not Modify!)
#define BOARD_P0_6_CMP_INPUT 				1


// P0_7 ADC12 instance number (Do Not Modify!)
#define BOARD_P0_7_ADC12_INSTANCE 				1
// P0_7 ADC12 input number (Do Not Modify!)
#define BOARD_P0_7_ADC12_INPUT 				1

// P0_7 ADC24 negative input number (Do Not Modify!)
#define BOARD_P0_7_ADC24_NEGATIVE_INPUT 				3

// P0_7 CMP instance number (Do Not Modify!)
#define BOARD_P0_7_CMP_INSTANCE 				1
// P0_7 CMP input number (Do Not Modify!)
#define BOARD_P0_7_CMP_INPUT 				1


// P1_0 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_0_ADC12_INSTANCE 				1
// P1_0 ADC12 input number (Do Not Modify!)
#define BOARD_P1_0_ADC12_INPUT 				2

// P1_0 CMP instance number (Do Not Modify!)
#define BOARD_P1_0_CMP_INSTANCE 				2
// P1_0 CMP input number (Do Not Modify!)
#define BOARD_P1_0_CMP_INPUT 				1


// P1_1 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_1_ADC12_INSTANCE 				1
// P1_1 ADC12 input number (Do Not Modify!)
#define BOARD_P1_1_ADC12_INPUT 				3

// P1_1 CMP instance number (Do Not Modify!)
#define BOARD_P1_1_CMP_INSTANCE 				3
// P1_1 CMP input number (Do Not Modify!)
#define BOARD_P1_1_CMP_INPUT 				1


// P1_2 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_2_ADC12_INSTANCE 				1
// P1_2 ADC12 input number (Do Not Modify!)
#define BOARD_P1_2_ADC12_INPUT 				4

// P1_2 CMP instance number (Do Not Modify!)
#define BOARD_P1_2_CMP_INSTANCE 				2
// P1_2 CMP input number (Do Not Modify!)
#define BOARD_P1_2_CMP_INPUT 				3


// P1_3 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_3_ADC12_INSTANCE 				1
// P1_3 ADC12 input number (Do Not Modify!)
#define BOARD_P1_3_ADC12_INPUT 				5

// P1_3 CMP instance number (Do Not Modify!)
#define BOARD_P1_3_CMP_INSTANCE 				3
// P1_3 CMP input number (Do Not Modify!)
#define BOARD_P1_3_CMP_INPUT 				3


// P1_4 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_4_ADC12_INSTANCE 				2
// P1_4 ADC12 input number (Do Not Modify!)
#define BOARD_P1_4_ADC12_INPUT 				0

// P1_4 CMP instance number (Do Not Modify!)
#define BOARD_P1_4_CMP_INSTANCE 				0
// P1_4 CMP input number (Do Not Modify!)
#define BOARD_P1_4_CMP_INPUT 				2


// P1_5 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_5_ADC12_INSTANCE 				2
// P1_5 ADC12 input number (Do Not Modify!)
#define BOARD_P1_5_ADC12_INPUT 				1

// P1_5 CMP instance number (Do Not Modify!)
#define BOARD_P1_5_CMP_INSTANCE 				1
// P1_5 CMP input number (Do Not Modify!)
#define BOARD_P1_5_CMP_INPUT 				2


// P1_6 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_6_ADC12_INSTANCE 				2
// P1_6 ADC12 input number (Do Not Modify!)
#define BOARD_P1_6_ADC12_INPUT 				2

// P1_6 CMP instance number (Do Not Modify!)
#define BOARD_P1_6_CMP_INSTANCE 				2
// P1_6 CMP input number (Do Not Modify!)
#define BOARD_P1_6_CMP_INPUT 				2


// P1_7 ADC12 instance number (Do Not Modify!)
#define BOARD_P1_7_ADC12_INSTANCE 				2
// P1_7 ADC12 input number (Do Not Modify!)
#define BOARD_P1_7_ADC12_INPUT 				3

// P1_7 CMP instance number (Do Not Modify!)
#define BOARD_P1_7_CMP_INSTANCE 				3
// P1_7 CMP input number (Do Not Modify!)
#define BOARD_P1_7_CMP_INPUT 				2


// P2_0 ADC12 instance number (Do Not Modify!)
#define BOARD_P2_0_ADC12_INSTANCE 				2
// P2_0 ADC12 input number (Do Not Modify!)
#define BOARD_P2_0_ADC12_INPUT 				4


// P2_1 ADC12 instance number (Do Not Modify!)
#define BOARD_P2_1_ADC12_INSTANCE 				2
// P2_1 ADC12 input number (Do Not Modify!)
#define BOARD_P2_1_ADC12_INPUT 				1

// P2_2 DAC12 instance number (Do Not Modify!)
#define BOARD_P2_2_DAC12_INSTANCE 				0
// P2_3 DAC12 instance number (Do Not Modify!)
#define BOARD_P2_3_DAC12_INSTANCE 				1
// P2_4 LPCMP input number (Do Not Modify!)
#define BOARD_P2_4_LPCMP_INPUT 				0

// P2_5 LPCMP input number (Do Not Modify!)
#define BOARD_P2_5_LPCMP_INPUT 				1

// P2_6 LPCMP input number (Do Not Modify!)
#define BOARD_P2_6_LPCMP_INPUT 				2

// P2_7 LPCMP input number (Do Not Modify!)
#define BOARD_P2_7_LPCMP_INPUT 				3

// </h>